theme: jekyll-theme-minimal
title: "Bilal Demirci"
description: "Bilal Demirci'nin kişisel blogu"
show_downloads: false
url: "http://www.bilaldemirci.com"

# Google Analytics
ga_track_id: 'UA-1390873-5'

# Build settings
markdown: kramdown
permalink: pretty